
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";




const App = lazy(() => import("./pages/App.tsx"));
const DonateGiftInKind = lazy(() => import("./pages/DonateGiftInKind.tsx"));
const Fundraise = lazy(() => import("./pages/Fundraise.tsx"));
const NotFoundPage = lazy(() => import("./pages/NotFoundPage.tsx"));
const WishStory = lazy(() => import("./pages/WishStory.tsx"));

export const userRoutes: RouteObject[] = [



	{ path: "/", element: <App />},
	{ path: "/donate-gift-in-kind-template", element: <DonateGiftInKind />},
	{ path: "/donate-gift-template", element: <DonateGiftInKind />},
	{ path: "/fundraise", element: <Fundraise />},
	{ path: "/not-found-page", element: <NotFoundPage />},
	{ path: "/notfoundpage", element: <NotFoundPage />},
	{ path: "/wish-story", element: <WishStory />},
	{ path: "/wishstory", element: <WishStory />},
	{ path: "/*", element: <App />},
];
